version: '3.9'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    build:
      context: ./backend/
    env_file: .env
    ports:
    - 8000:8000
    volumes:
      - static:/app/static
      - media:/app/media
      - ../data:/app/data
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  
  gateway:
    build:
      context: ./nginx/
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
    ports:
      - 80:80